spring:
    profiles:
        active: 
        -   dog
        -   EN
        -   prod

guru:
    username: YmlUserName
    password: YmlPassword
    jdbcurl: YmlUrl

---
spring:
    config:
        activate:
            on-profile: prod

guru:
    username: YmlProdDBUser
    password: YmlProdPassword
    jdbcurl: YmlProdUrl
